#!/usr/bin/python3
import cbus
nodes=cbus.cbus_read_nodes('gen','file://MAIN_address.xml')
cbus.bus_delay(100)
print("Test the ID")
print ("ID read:"+ hex(nodes['ID'].read()))
print ("VER read:"+ hex(nodes['VER'].read()))
cbus.bus_delay(250)
print("LINKS1 ID read:"+hex(nodes['LINKS[0].ID'].read()))
print("LINKS1 VER read:"+hex(nodes['LINKS[0].VER'].read()))
cbus.bus_delay(250)
print("LINKS1 STATUS read:"+hex(nodes['LINKS[0].STATUS'].read()))
cbus.bus_delay(250)
print("LINKS1 CTRL.START write")
nodes['LINKS[0].CTRL.START'].write(1)
cbus.bus_delay(250)
print("LINKS4 STATUS read:"+hex(nodes['LINKS[4].STATUS'].read()))
cbus.bus_delay(250)
print("Now we test bitfields")
print("LINKS4 CTRL.START write")
nodes['LINKS[4].CTRL.START'].write(1)
nodes['CTRL.CLK_ENABLE'].write(1)
cbus.bus_delay(30)
nodes['CTRL.CLK_FREQ'].write(0xc)
cbus.bus_delay(30)
nodes['CTRL.PLL_RESET'].write(1)
cbus.bus_delay(30)
nodes['CTRL.CLK_ENABLE'].write(0)
cbus.bus_delay(30)
nodes['CTRL.CLK_FREQ'].write(0x5)
cbus.bus_delay(30)
nodes['CTRL.PLL_RESET'].write(0)
print("Now we test the blackbox")
nodes['EXTERN[0].REG1'].write(0x5)
print("EXTERN[0] REG1 read:"+hex(nodes['EXTERN[0].REG1'].read()))
nodes['EXTERN[1].REG0'].write(0x76)
print("EXTERN[1] REG2 read:"+hex(nodes['EXTERN[1].REG2'].read()))
print("And again we read the LINKS1 ID and version")
print("LINKS1 ID read:"+hex(nodes['LINKS[0].ID'].read()))
print("LINKS1 VER read:"+hex(nodes['LINKS[0].VER'].read()))
cbus.bus_delay(3000)



